name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Show Chrome path
        run: echo "CHROME PATH = $(which google-chrome)"

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Запуск приложения
      - name: Run IBank App
        run: |
          nohup java -jar artifacts/app-ibank-build-for-testers.jar > app.log 2>&1 &
          sleep 7

      - name: Check server availability
        run: |
          for i in {1..10}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:9999)
            if [ "$STATUS" = "200" ]; then
              echo "Server is UP!"
              exit 0
            fi
            echo "Waiting for server..."
            sleep 2
          done
          echo "Server failed to start"
          cat app.log
          exit 1

      - name: Run Tests
        env:
          CHROME_BIN: /usr/bin/google-chrome
        run: |
          ./gradlew clean test \
            -Dselenide.browser=chrome \
            -Dselenide.headless=true \
            -Dchromeoptions.args="--no-sandbox,--disable-dev-shm-usage,--disable-gpu,--remote-allow-origins=*"
